### ISSUE TITLE
搜索时，若关键字包含中文，会造成页面出错。

### ISSUE THREAD

**Issue by oyiadin** [BuildFarBox/doc.farbox.com#2]
就像这样 [/?s=日期](http://doc.farbox.com/?s=%E6%97%A5%E6%9C%9F)，不知道是代码的问题还是我本地环境的问题。

**Comment by hepochen** [comment]
URL格式的，进入NanoWork后转成了UTF8格式的，再进入到主服务的时候，编码出现了错误。:(

**Comment by oyiadin** [comment]
想知道为什么编码错误会导致这种情况……不应该的样子啊。

**Comment by hepochen** [comment]
@oyiadin URL格式，比如类似`%2F`的，进入Nano的系统后，会全部转为Unicode编码，在Nano向主服务器请求的时候，又统一使用UTF8的编码。

a_with_selected这个函数是运行在主服务器中的环境，如果没有Nano在中间 ，它处理的都是URL格式类型或者Unicode的，可以与其它Unicode的字符进行相加；过了一遍Nano的系统，拿到的是转义后的字符，跟Unicode叠加的时候，会产生UnicodeDecodeError之类的错误。

**Comment by oyiadin** [comment]
@hepochen thx，大致知道什么回事了~

**Comment by hepochen** [comment]
@oyiadin 客气了，应该感谢晓源；这个bug没有处于检测的范围，默认是假设a_with_selected之类的函数是不会出错的，所以出错了，给出debug信息到浏览器之后，服务器实际上不知道自己出错了…… 囧
